name: Build Neva/Magis firmware

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The printer version (values: [V1, V1Mod, Magis]) :'
        required: true
        default: 'Magis'

jobs:
  firmware-compilation-checks:
    name: Neva/Magis firmware compilation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Apply selected configuration
      run: ./LinuxAddons/Dagoma/bin/apply_configuration -gcof Neva version:${{ github.event.inputs.version }}
    - name: Run PlatformIO
      run: platformio run --environment megaatmega2560
    - name: Archive compiled firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/megaatmega2560/firmware.hex